version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis_alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./volumes/redis/data:/var/lib/redis
      - ./volumes/redis/conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - default
  postgresql:
    image: postgres:latest
    container_name: postgresql_latest
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    networks:
      - default
  api-service:
    image: ${APP_NAME}:1.0.0
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/${APP_NAME}
      - /${APP_NAME}/node_modules
    external_links:
      - ${LINK_REDIS}:${LINK_REDIS}
      - ${LINK_MONGODB}:${LINK_MONGODB}
    networks:
      - default
networks:
  default:
    external: true
    name: boilerplate-nestjs

